### ISSUE TITLE
hi,hi.Maybe I find a bug.

### ISSUE THREAD

**Issue by FreddyMeepo** [picketlink/picketlink-idm#1]
Version 1.4.1.Final:
in the file 
picketlink-idm-auth\src\main\java\org\picketlink\idm\auth\JBossIdentityIDMLoginModule.java

at line 196 and  line 312

the code 
  ids.beginTransaction(); 
should be deleted?

I don't konw if i am right ,please tell me,OK? thanks a lot!

**Comment by bdaw** [comment]
Hmm... I don't think anyone was really maintaining this code recently. It was implemented for JBoss AS 5 and should be removed at this point probably. 

If you confirm with which AS version you have verified it and send a PR I can merge it.

**Comment by FreddyMeepo** [comment]
Thanks a lot for reply!

 I want to use idm 1.4.1.Final working with PicketLink(version2,1.5) idp on
JBoss AS 7.1.
So,i modified the standalone.xml like this:
              <security-domain name="idp" cache-type="default">
                    <authentication>
                        <login-module code="custom.MyModule"
flag="required">
                            <module-option name="realmName"
value="realm://JBossIdentity"/>
                            <module-option
name="identitySessionFactoryJNDIName" value="java:/IdentitySessionFactory"/>
                            <module-option name="transactionAware"
value="true"/>
                        </login-module>
                    </authentication>
                    <audit>
                        <provider-module
code="org.picketlink.identity.federation.core.audit.PicketLinkAuditProvider"/>
                    </audit>
                </security-domain>
and MyModule.java gos like this:

public class MyModule extends JBossIdentityIDMLoginModule {
private IdentitySessionFactory identitySessionFactory;

public boolean login() throws LoginException {
return super.login();
}

protected IdentitySessionFactory getIdentitySessionFactory()
throws NamingException {
if (identitySessionFactory == null) {
try {
identitySessionFactory = new IdentityConfigurationImpl()
.configure("example-db-config.xml")
.buildIdentitySessionFactory();
} catch (IdentityConfigurationException e) {
// TODO Auto-generated catch block
e.printStackTrace();
}
}
return identitySessionFactory;
}

}
beacause i don't know how to configure the JNDI
"java:/IdentitySessionFactory"(Perhaps you can help me at this).
and i find this issue while debugging.

Thanks a lot for helping,My i konw which version should i use and how can
it work with PicketLink and JBoss AS7?
Cuz i am a noob of AS7,so confused about the configuration.

在 2012年12月30日星期日，Boleslaw Dawidowicz 写道：

**Comment by pedroigor** [comment]
This repository is no longer maintained and is archived. For more details, please take a look at http://picketlink.org/keycloak-merge-faq.
